### ISSUE TITLE
This looks very promising!

### ISSUE THREAD

**Issue by evandarcy** [luisfonsivevo/physx.js#1]

**Comment by evandarcy** [comment]
We are also working on a JS port of PhysX. Did you get this far from scratch? I'd love to hear more about it. You can email me at evan@robotify.com

**Comment by evandarcy** [comment]
Have you worked with Three.js before?

**Comment by luisfonsivevo** [comment]
closing this because "Issues 1" irrationally stresses me out + we already emailed
